- name: "Config cron daemon for Ubuntu"
  ansible.builtin.include_tasks: ubuntu/main.yml
  when: ansible_distribution == "Ubuntu"

- name: "Config cron daemon for Arch Linux"
  ansible.builtin.include_tasks: archlinux/main.yml
  when: ansible_os_family == "Archlinux"

